import character from './character';
import episode from './episode';
import book from './book';
import blogPost from './blogPost';
import product from './product';
import category from './category';
import faq from './faq';
import page from './page';
import siteSettings from './siteSettings';
import legalPage from './legalPage';
export const schemaTypes = [siteSettings, character, episode, book, blogPost, product, category, faq, page, legalPage];
